name: 'Update Submodule Action'
on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: update-submodules-famaf

env:
  STATUS_COMMITS: ''

jobs:
  famaftestupdate:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          submodules: recursive
          # submodules: true
      - name: Update submodules
        run: git submodule update --init --recursive --checkout -f --remote
        #-- "${{github.event.client_payload.module}}"

      - name: Update status
        id: status
        run: |
          echo "status=$(git status -s)" >> $STATUS_COMMITS
        # $GITHUB_OUTPUT
        # echo "::set-output name={status}::{status}"
        # echo "::set-output name=status::$(git status -s)"

      - name: Config git
        if: $STATUS_COMMITS != ''
        # if: ${{ steps.status.outputs.status }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "[BOT] Update submodules at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")" || echo "No changes to commit"

      - name: Push updates
        if: ${{ steps.status.outputs.status && github.event_name == 'push' }}
        run: git push
