name: 'Workflow triggered from parent'
on:
  repository_dispatch:
    types: [update-submodules-famaf]

jobs:
  updateSubmodules:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Triggering Wokflow Trigger"